package com.github.gchudnov.bscript.serde.internal

object Keys:
  val kind: String          = "kind"
  val value: String         = "value"
  val id: String            = "id"
  val name: String          = "name"
  val symbol: String        = "symbol"
  val expr: String          = "expr"
  val lhs: String           = "lhs"
  val rhs: String           = "rhs"
  val a: String             = "a"
  val b: String             = "b"
  val elements: String      = "elements"
  val statements: String    = "statements"
  val params: String        = "params"
  val args: String          = "args"
  val fields: String        = "fields"
  val body: String          = "body"
  val cond: String          = "cond"
  val then1: String         = "then1"
  val else1: String         = "else1"
  val xType: String         = "type"
  val retType: String       = "retType"
  val elementType: String   = "elementType"
